version: 2.1

jobs:
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: Setup .npmrc credentials
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm run build
      - run: npm publish

workflows:
  version: 2
  publish:
    jobs:
      - publish:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
